// <auto-generated />
namespace Flicks315.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MovieInitialSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieInitialSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201503311610017_MovieInitialSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
